In [1]:
import pandas as pd
import os
from tqdm import tqdm

In [2]:
import pickle

In [3]:
with open("BlogNemo/add_id.pkl", "rb") as fp:
    id_list = pickle.load(fp)

In [4]:
id_dict = {i : ele[1] for i,ele in enumerate(id_list)}

In [ ]:
id_dict

In [13]:
# !rm -f /workspace/nemo_datasets/phu_classifier_filtering/*

In [14]:
!ls -lh /workspace/nemo_datasets/phu_classifier_filtering/

total 0

In [5]:
len_ds = len(os.listdir('/workspace/nemo_datasets/add_id'))
for i in tqdm(range(len_ds)):
    if f'{i}.parquet' in os.listdir('/workspace/nemo_datasets/phu_classifier_filtering/'):
        continue
    df_result = pd.read_parquet(f'/workspace/nemo_datasets/result/{id_dict[i]}.parquet', engine='pyarrow')
    df_now = pd.read_parquet(f'/workspace/nemo_datasets/classifier_filtering/data/hq.parquet/part.{i}.parquet', engine='pyarrow')
    

    result = pd.merge(df_result, df_now, on=['id'], how='inner')
    
    result.rename(columns={'filename_x' : 'filename','text_x' : 'text'}, inplace=True)
    result.drop(['filename_y', 'text_y'], axis=1, inplace=True)
    #     result.to_parquet(f'/workspace/nemo_datasets/result/{i}.parquet', engine='pyarrow')
#     result.head()
    print(len(result))
    result.to_parquet(f'/workspace/nemo_datasets/phu_classifier_filtering/{i}.parquet', engine='pyarrow')

  0%|                                                                                           | 0/256 [00:00<?, ?it/s]

46006

 90%|█████████████████████████████████████████████████████████████████████████        | 231/256 [00:31<00:01, 14.86it/s]

46061

 91%|█████████████████████████████████████████████████████████████████████████▍       | 232/256 [00:33<00:04,  5.62it/s]

46428

 91%|█████████████████████████████████████████████████████████████████████████▋       | 233/256 [00:49<00:07,  3.20it/s]

46094

 91%|██████████████████████████████████████████████████████████████████████████       | 234/256 [01:04<00:10,  2.01it/s]

45819

 92%|██████████████████████████████████████████████████████████████████████████▎      | 235/256 [01:20<00:15,  1.31it/s]

46115

 92%|██████████████████████████████████████████████████████████████████████████▋      | 236/256 [01:36<00:22,  1.12s/it]

46374

 93%|██████████████████████████████████████████████████████████████████████████▉      | 237/256 [01:52<00:30,  1.62s/it]

45689

 93%|███████████████████████████████████████████████████████████████████████████▎     | 238/256 [02:07<00:40,  2.26s/it]

46416

 93%|███████████████████████████████████████████████████████████████████████████▌     | 239/256 [02:24<00:53,  3.13s/it]

46088

 94%|███████████████████████████████████████████████████████████████████████████▉     | 240/256 [02:40<01:06,  4.18s/it]

46281

 94%|████████████████████████████████████████████████████████████████████████████▎    | 241/256 [02:57<01:21,  5.46s/it]

45882

 95%|████████████████████████████████████████████████████████████████████████████▌    | 242/256 [03:14<01:36,  6.87s/it]

46283

 95%|████████████████████████████████████████████████████████████████████████████▉    | 243/256 [03:29<01:47,  8.25s/it]

46093

 95%|█████████████████████████████████████████████████████████████████████████████▏   | 244/256 [03:46<01:57,  9.79s/it]

46398

 96%|█████████████████████████████████████████████████████████████████████████████▌   | 245/256 [04:02<02:00, 10.99s/it]

45949

 96%|█████████████████████████████████████████████████████████████████████████████▊   | 246/256 [04:18<02:01, 12.15s/it]

46248

 96%|██████████████████████████████████████████████████████████████████████████████▏  | 247/256 [04:34<01:58, 13.16s/it]

45854

 97%|██████████████████████████████████████████████████████████████████████████████▍  | 248/256 [04:51<01:52, 14.02s/it]

46284

 97%|██████████████████████████████████████████████████████████████████████████████▊  | 249/256 [05:06<01:41, 14.49s/it]

46022

 98%|███████████████████████████████████████████████████████████████████████████████  | 250/256 [05:22<01:28, 14.80s/it]

45876

 98%|███████████████████████████████████████████████████████████████████████████████▍ | 251/256 [05:38<01:15, 15.10s/it]

45966

 98%|███████████████████████████████████████████████████████████████████████████████▋ | 252/256 [05:53<01:00, 15.22s/it]

45993

 99%|████████████████████████████████████████████████████████████████████████████████ | 253/256 [06:09<00:46, 15.49s/it]

45875

 99%|████████████████████████████████████████████████████████████████████████████████▎| 254/256 [06:26<00:31, 15.71s/it]

46152

100%|████████████████████████████████████████████████████████████████████████████████▋| 255/256 [06:42<00:15, 15.80s/it]

45784

100%|█████████████████████████████████████████████████████████████████████████████████| 256/256 [06:58<00:00,  1.63s/it]

In [4]:
result = pd.merge(df_result, df_now, on=['id'], how='inner')

In [8]:
result = pd.merge(df_result, df_now, on=['id'], how='inner')

In [31]:
df1 = pd.read_parquet(f'/workspace/nemo_datasets/phu_classifier_filtering/1.parquet', engine='pyarrow')

In [32]:
df1

,filename,text,id,domain,sentiment,quality_score
0,1.parquet,Hóa phân tích là bộ môn của ngành hóa học nghi...,VI_open-0000455195,Science,1,0.902657
1,1.parquet,"Yahoo! Inc. là một tập đoàn đại chúng Hoa Kỳ, ...",VI_open-0000455197,Internet_and_Telecom,1,0.885266
2,1.parquet,Trôi dạt lục địa là sự chuyển động tương đối v...,VI_open-0000455199,Science,1,0.871920
3,1.parquet,Tòa án Tối cao Hoa Kỳ (tiếng Anh: Supreme Cour...,VI_open-0000455201,Law_and_Government,1,0.730876
4,1.parquet,"Trà (hay chè theo phương Bắc bộ, tên khoa học...",VI_open-0000455203,Food_and_Drink,1,0.949346
...,...,...,...,...,...,...
51334,1.parquet,"Đất mặt tiền Nguyễn Trung Trực, chính chủ, shr...",VI_open-0000910357,Real_Estate,0,0.029701
51335,1.parquet,"Ghế kết hợp giường gỗ - tiết kiệm, hiện đại và...",VI_open-0000910358,Home_and_Garden,1,0.181226
51336,1.parquet,> Văn hóa ứng xử chốn công sở > Những điều nên...,VI_open-0000910380,Business_and_Industrial,1,0.009113
51337,1.parquet,[Người ẩn hình] - Chương 10 - ♥•.¸¸.•♥• Hiền L...,VI_open-0000910382,Books_and_Literature,1,0.260911
51338,1.parquet,STYX: SHARDS OF DARKNESS - Game Stealth Action...,VI_open-0000910386,Games,1,0.659311

In [7]:
df_domain = pd.read_parquet(f'/workspace/nemo_datasets/labeling_dataset/0.parquet', engine='pyarrow')

In [8]:
df_sentiment = pd.read_parquet(f'/workspace/nemo_datasets/sentiment_dataset/0.parquet', engine='pyarrow')

In [12]:
result = pd.merge(df_domain, df_sentiment, on=['id','filename','text'], how='left')

In [13]:
result

,filename,text,id,label_x,label_y
0,0.parquet,Internet Society hay ISOC là một tổ chức quốc ...,VI_open-0000000000,Internet_and_Telecom,1
1,0.parquet,Tế bào là một đơn vị cấu trúc cơ bản có chức n...,VI_open-0000000001,Science,1
2,0.parquet,Quẻ Phong Thiên Tiểu Súcđồ hình |||:|| còn gọi...,VI_open-0000000002,Books_and_Literature,1
3,0.parquet,Google LLC () là một công ty công nghệ đa quốc...,VI_open-0000000003,News,1
4,0.parquet,"Nguyên tố vi lượng, còn được gọi là vi lượng t...",VI_open-0000000004,Science,1
...,...,...,...,...,...
455189,0.parquet,Hà Tĩnh 16/09/18 13:38 GMT+7 2 liên quan Gốc R...,VI_open-0000455189,People_and_Society,0
455190,0.parquet,"Ba đợt ""sóng"" địa chính trị trên biển Đông Chu...",VI_open-0000455190,People_and_Society,1
455191,0.parquet,ĐAN QUANG TÂM Advertisements hoang 18.12.2013 ...,VI_open-0000455191,Arts_and_Entertainment,0
455192,0.parquet,"#KTX_CFS6973 ---------- #1 1/6/2018 20:40:59 ""...",VI_open-0000455192,Computers_and_Electronics,1
455193,0.parquet,"Giá gạt tàn, gạt tàn xì gà Cohiba 830 - 3A chí...",VI_open-0000455193,Shopping,1

In [14]:
df1

,filename,text,id
0,0.parquet,Internet Society hay ISOC là một tổ chức quốc ...,VI_open-0000000000
1,0.parquet,Tế bào là một đơn vị cấu trúc cơ bản có chức n...,VI_open-0000000001
2,0.parquet,Quẻ Phong Thiên Tiểu Súcđồ hình |||:|| còn gọi...,VI_open-0000000002
3,0.parquet,Google LLC () là một công ty công nghệ đa quốc...,VI_open-0000000003
4,0.parquet,"Nguyên tố vi lượng, còn được gọi là vi lượng t...",VI_open-0000000004
...,...,...,...
455189,0.parquet,Hà Tĩnh 16/09/18 13:38 GMT+7 2 liên quan Gốc R...,VI_open-0000455189
455190,0.parquet,"Ba đợt ""sóng"" địa chính trị trên biển Đông Chu...",VI_open-0000455190
455191,0.parquet,ĐAN QUANG TÂM Advertisements hoang 18.12.2013 ...,VI_open-0000455191
455192,0.parquet,"#KTX_CFS6973 ---------- #1 1/6/2018 20:40:59 ""...",VI_open-0000455192
455193,0.parquet,"Giá gạt tàn, gạt tàn xì gà Cohiba 830 - 3A chí...",VI_open-0000455193